spring:
  application:
    name: gateway
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029
      config:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029
        file-extension: yaml
  config:
    import:
      - nacos:actuator.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true