spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        namespace: 122b6435-5eaf-4232-af57-7bf6e576870c
      config:
        namespace: 122b6435-5eaf-4232-af57-7bf6e576870c
      server-addr: ${SERVER_URL:127.0.0.1}:8848
  config:
    import:
      - nacos:actuator.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true