spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.187.128:3306/basic-examples?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080

server:
  port: 8000

basic:
  cloud:
    doc:
      security:
        - name: authorization_code
          access-token-url: http://127.0.0.1:8080/oauth2/token
          authorize-url: http://127.0.0.1:8080/oauth2/authorize
          grant-type: authorization_code
          scopes:
            - name: openid
              description: Openid Connect Id Token
            - name: profile
              description: 用户信息
        - name: password
          access-token-url: http://127.0.0.1:8080/oauth2/token
          authorize-url: http://127.0.0.1:8080/oauth2/authorize
          grant-type: password
          scopes:
            - name: openid
              description: Openid Connect Id Token
            - name: profile
              description: 用户信息