spring:
  application:
    name: system
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029
      config:
        namespace: a29400b0-9f79-47a0-80df-6ceab61d3029

  config:
    import:
      - nacos:spring-doc.yaml?refresh=true
      - nacos:${spring.application.name}.yaml?refresh=true